name: Upload New Consultant Roster

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: choice
        options:
          - dev
          - prod
        required: true
      web_app_url:
        description: "Web App URL for the Google Sheet"
        required: true
      sheet_name:
        description: "Sheet name to process"
        required: true

jobs:
  run-pipeline:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 --decode > /tmp/gcp-key.json

        # Debugging: Check if the file exists
        if [ -f /tmp/gcp-key.json ]; then
            echo "Decoded JSON file created successfully."
        else
            echo "Failed to create decoded JSON file."
            exit 1
        fi

        # Debugging: Validate the JSON file
        echo "Validating the JSON file..."
        echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 --decode
        python -m json.tool /tmp/gcp-key.json || echo "Invalid JSON file."

        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp-key.json"

    # Step 4: Run the pipeline script
    - name: Run New Consultant Pipeline
      env:
        CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ vars.DB_NAME }}
        WEB_APP_URL: ${{ github.event.inputs.web_app_url }}
        SHEET_NAME: ${{ github.event.inputs.sheet_name }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
      run: |
        python pipelines/new-consultant-pipeline.py